export {
	BRANCH_SUMMARY_PROMPT_FILE_NAME,
	COMPACTION_PROMPT_FILE_NAME,
	CONFIG_FILE_NAME,
	getScopedPaths,
	loadConfig,
	loadEditableScopedConfig,
	loadEffectiveConfig,
	loadScopedConfig,
	readTextFileIfExists,
	resetLiveCompactionScope,
	resolveLiveCompactionPaths,
	saveScopedConfig,
	scopeHasLocalOverrides,
	writeTextFile,
} from '@live-compaction/config/io';
export {
	DEFAULT_BRANCH_SUMMARY_PROMPT_CONTRACT,
	DEFAULT_BRANCH_SUMMARY_TEMPLATE_BODY,
	DEFAULT_COMPACTION_PROMPT_CONTRACT,
	DEFAULT_COMPACTION_TEMPLATE_BODY,
	deleteScopedPrompt,
	loadBranchSummaryPromptContract,
	loadCompactionPromptContract,
	loadEffectiveBranchSummaryPromptContract,
	loadEffectiveCompactionPromptContract,
	loadScopedPromptText,
	resolveEffectivePrompt,
	saveScopedPromptText,
} from '@live-compaction/config/prompts';
export type {
	ConfigScope,
	IncludeFilesTouchedSettings,
	LiveCompactionConfig,
	LiveCompactionPaths,
	PanelScope,
	PresetConfig,
	PromptKind,
	PromptResolution,
	ThinkingLevel,
} from '@live-compaction/config/schema';
export {
	CURRENT_PRESET_SENTINEL,
	DEFAULT_CONFIG,
	normalizeOptionalText,
	normalizeThinkingLevel,
	PANEL_SCOPE_VALUES,
	parseConfig,
} from '@live-compaction/config/schema';
